# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A simple blog | micke239
description: > # this means to ignore newlines until "baseurl:"
  micke239 writing about stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://micke239.github.io" # the base hostname & protocol for your site
twitter_username: micke239
github_username:  micke239

# Build settings
markdown: kramdown

# header
header:
  title: A simple blog
  summary: micke239.github.io
